In [2]:
import torch
import numpy as np

数据类型自动识别

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

从另一个tensor

In [5]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [16]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand

tensor([[0.9476, 0.1044],
        [0.4910, 0.8002]])

In [21]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.5402, 0.9515, 0.4384],
        [0.8584, 0.8405, 0.6437]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [22]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [25]:
print(f"Is CUDA available: {torch.cuda.is_available()}")

if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    
print(f"tenor is now on:{tensor.device}")

Is CUDA available: True
tenor is now on:cuda:0


标准numpy操作

In [29]:
tensor = torch.ones(4,4)
print(f"First row:{tensor[0]}")
print(f"First column:{tensor[:,0]}")
print(f"Last column:{tensor[...,-1]}")
tensor[:,1] = 0
print(tensor)

First row:tensor([1., 1., 1., 1.])
First column:tensor([1., 1., 1., 1.])
Last column:tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [34]:
t1 = torch.cat([tensor,tensor,tensor],dim=0)
t1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [39]:
y1 = tensor @ tensor.T
print(f"the tensor is: \n {y1} \n")
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor,tensor.T,out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)
#output

the tensor is: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [40]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [41]:
print(f"{tensor} \n")
print(f"{tensor.add(5)} \n")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 



In [42]:
t = torch.ones(5)
print(f"t:{t}")
n = t.numpy()
print(f"n:{n}")

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


In [43]:
t.add_(1)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]
